[project]
name = "lofi-news"
version = "0.1.0"
description = "An RSS aggregator built with Django and Datastar"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4==4.14.3",
    "datastar-py==1.0.2",
    "django==6.0.6",
    "django-debug-toolbar==6.3.0",
    "django-vite==3.1.0",
    "feedparser==6.0.12",
    "playwright>=1.60.0",
]

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E402", "E501", "F403"]

