# Generated by Django 6.0.6 on 2026-06-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
