# Generated by Django 6.0.6 on 2026-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_datasource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='original_url',
            field=models.URLField(null=True),
        ),
    ]
