# Generated by Django 6.0.6 on 2026-06-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_story_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
