# Generated by Django 6.0.6 on 2026-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_datasource_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='raw_data',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
