# Generated by Django 6.0.6 on 2026-06-06 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['story_id', 'user_id'], name='frontend_vo_story_i_0e273f_idx'),
        ),
    ]
