# Generated by Django 6.0.6 on 2026-06-13 00:08

import django.db.models.deletion
import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='settings',
            field=models.JSONField(default=frontend.models.user_profile_default_value, verbose_name='settings'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.channel'),
        ),
    ]
